title: Sherry Luo
description: Personal website, M.Sc. in Statistics @ McMaster
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
